Change default shell to zsh, minor fixes in i3blocks scripts

diff --git a/.local/bin/pkg-not-found b/.local/bin/pkg-not-found
--- a/.local/bin/pkg-not-found
+++ b/.local/bin/pkg-not-found
@@ -1,30 +1,13 @@
-#!/bin/bash
+command_not_found_handler() {
+  local pkgs cmd="$1"
 
-command_not_found_handle () {
-  local pkgs cmd=$1
-  local FUNCNEST=10
-
-  set +o verbose
-
-  mapfile -t pkgs < <(pkgfile -bv -- "${cmd}" 2>/dev/null)
-
-  if [[ ${#pkgs[*]} -eq 1 && -n ${PKGFILE_PROMPT_INSTALL_MISSING} ]]; then
-    local pkg=${pkgs[0]%% *}
-    local response
-
-    read -r -p "Install ${pkg}? [Y/n] " response
-    [[ -z ${response} || ${response} = [Yy] ]] || return 0
-    printf '\n'
-    sudo pacman -S --noconfirm -- "${pkg}"
-    return
-  fi
-
-  if (( ${#pkgs[*]} )); then
-    printf '%s may be found in the following packages:\n' "${cmd}"
-    printf '  %s\n' "${pkgs[@]}"
+  pkgs=(${(f)"$(pkgfile -b -v -- "$cmd" 2>/dev/null)"})
+  if [[ -n "$pkgs" ]]; then
+    printf '%s may be found in the following packages:\n' "$cmd"
+    printf '  %s\n' $pkgs[@]
   else
-    printf "bash: %s: command not found\n" "${cmd}"
-  fi >&2
+    printf 'zsh: command not found: %s\n' "$cmd"
+  fi 1>&2
 
   return 127
 }
